[package]
name = "sandbox_guessing_game"
version = "0.1.1"
authors = ["Thiago Arrais <thiago.arrais@gmail.com>"]
edition = "2018"
description = "The guessing game from the Rust book"
license = "MIT"
repository = "https://github.com/thiagoarrais/guessing_game.git"

[dependencies]

rand = "0.3.14"
